/* Simulation code for BouncingBallFMI20 generated by the OpenModelica Compiler OMCompiler v1.13.0-dev.1097+gde1221967. */
#if !defined(BouncingBallFMI20__MODEL_H)
#define BouncingBallFMI20__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "BouncingBallFMI20_functions.h"


extern void BouncingBallFMI20_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void BouncingBallFMI20_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int BouncingBallFMI20_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int BouncingBallFMI20_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int BouncingBallFMI20_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int BouncingBallFMI20_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int BouncingBallFMI20_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int BouncingBallFMI20_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int BouncingBallFMI20_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int BouncingBallFMI20_checkForAsserts(DATA *data, threadData_t *threadData);
extern int BouncingBallFMI20_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int BouncingBallFMI20_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int BouncingBallFMI20_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* BouncingBallFMI20_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* BouncingBallFMI20_relationDescription(int i);
extern void BouncingBallFMI20_function_initSample(DATA *data, threadData_t *threadData);
extern int BouncingBallFMI20_initialAnalyticJacobianG(void* data, threadData_t *threadData);
extern int BouncingBallFMI20_initialAnalyticJacobianA(void* data, threadData_t *threadData);
extern int BouncingBallFMI20_initialAnalyticJacobianB(void* data, threadData_t *threadData);
extern int BouncingBallFMI20_initialAnalyticJacobianC(void* data, threadData_t *threadData);
extern int BouncingBallFMI20_initialAnalyticJacobianD(void* data, threadData_t *threadData);
extern int BouncingBallFMI20_functionJacG_column(void* data, threadData_t *threadData);
extern int BouncingBallFMI20_functionJacA_column(void* data, threadData_t *threadData);
extern int BouncingBallFMI20_functionJacB_column(void* data, threadData_t *threadData);
extern int BouncingBallFMI20_functionJacC_column(void* data, threadData_t *threadData);
extern int BouncingBallFMI20_functionJacD_column(void* data, threadData_t *threadData);
extern const char* BouncingBallFMI20_linear_model_frame(void);
extern const char* BouncingBallFMI20_linear_model_datarecovery_frame(void);
extern int BouncingBallFMI20_mayer(DATA* data, modelica_real** res, short *);
extern int BouncingBallFMI20_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int BouncingBallFMI20_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int BouncingBallFMI20_setInputData(DATA *data, const modelica_boolean file);
extern int BouncingBallFMI20_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void BouncingBallFMI20_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void BouncingBallFMI20_function_updateSynchronous(DATA * data, threadData_t *threadData, long i);
extern int BouncingBallFMI20_function_equationsSynchronous(DATA * data, threadData_t *threadData, long i);
extern void BouncingBallFMI20_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void BouncingBallFMI20_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int BouncingBallFMI20_inputNames(DATA* data, char ** names);
extern int BouncingBallFMI20_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int BouncingBallFMI20_functionLocalKnownVars(DATA*, threadData_t*);
extern int BouncingBallFMI20_symbolicInlineSystem(DATA*, threadData_t*);

#include "BouncingBallFMI20_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(BouncingBallFMI20__MODEL_H) */


