# This file is part of JuliaFMI.
# License is MIT: https://servant-om.fh-bielefeld.de/gitlab/AnHeuermann/FMU_JL_Simulator/blob/master/LICENSE.txt

# This YAML file


stages:
  - build
  - load
  - test
  - deploy

jobs:
  stage: build
  script:
    - echo HelloWorld!
    - gcc --version
