# This file is part of JuliaFMI.
# License is MIT: https://servant-om.fh-bielefeld.de/gitlab/AnHeuermann/FMU_JL_Simulator/blob/master/LICENSE.txt

# This YAML file

stages:
  - build
  - load
  - test
  - deploy


before_script:
 - echo Starting script

build_c_file:
  stage: build
  script:
   - if [ ! -d ./bin/unix64/ ]; then mkdir ./bin/unix64/; fi
   - gcc -shared src/logger.c -fPIC -o bin/unix64/logger.so

build_julia_deps:
  stage: build
  script:
    - julia --version
    - julia deps/build.jl

check_julia_syntax:
  stage: load
  script:
    - julia src/FMI2Types.jl
    - julia src/FMICallbackFunctions.jl
    - julia src/FMIWrapper.jl
    - julia src/FMUSimulator.jl

HelloFMI20World.fmu:
  stage: test
  script:
    - julia -e "include(\"test/runtests.jl\"); testHelloFMI20World()"

BouncingBall.fmu:
  stage: test
  script:
    - julia -e "include(\"test/runtests.jl\"); testBouncingBall()"

deploy:
  stage: deploy
  script:
    - git --version

after_script:
  - rm -rf test/linuxFMU/FMU_*
  - echo cleaned tmp files up
