# This file is part of JuliaFMI.
# License is MIT: https://servant-om.fh-bielefeld.de/gitlab/AnHeuermann/FMU_JL_Simulator/blob/master/LICENSE.txt

os: linux
language: julia
julia:
  - 1.0.5
  - 1.3.0
  - nightly
matrix:
    allow_failures:
        - julia: nightly

before_install:
  - sudo apt-get update
  - sudo apt-get install libblas-dev liblapack-dev
  - sudo apt-get install -y build-essential

before_script:
  - cd test && git clone https://github.com/modelica/fmi-cross-check.git
  - cd ..
  - if [ ! -d ./bin/unix64/ ]; then mkdir ./bin/unix64/; fi
  - gcc -shared src/logger.c -fPIC -o bin/unix64/logger.so

jobs:
  script:
    - julia -e "using Pkg; Pkg.build(); Pkg.test(coverage=true)"
notifications:
  email: false
