# This file is part of JuliaFMI.
# Licensed under MIT: https://github.com/AnHeuermann/JuliaFMI/blob/master/LICENSE.txt

language: julia
julia:
  - 1.0.5
#  - 1.3.0

services:
  - docker

coveralls: true

env:
  global:
    - omc='docker run -it openmodelica/openmodelica:v1.13.2-minimal omc'

before_install:
  - sudo apt-get update
  - sudo apt-get install libblas-dev liblapack-dev
  - sudo apt-get install -y build-essential
  - docker pull openmodelica/openmodelica:v1.13.2-minimal
  - script: eval $omc --version

before_script:
  - cd test && git clone https://github.com/modelica/fmi-cross-check.git
  - cd ..
  - if [ ! -d ./bin/unix64/ ]; then mkdir ./bin/unix64/; fi
  - gcc -shared src/logger.c -fPIC -o bin/unix64/logger.so

job:
  script:
    - using Pkg
    - Pkg.build()
    - Pkg.test(coverage=true)

notifications:
  email: false
