/* Simulation code for HelloFMI20World generated by the OpenModelica Compiler OMCompiler v1.13.0-dev.1097+gde1221967. */
#if !defined(HelloFMI20World__MODEL_H)
#define HelloFMI20World__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "HelloFMI20World_functions.h"


extern void HelloFMI20World_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void HelloFMI20World_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int HelloFMI20World_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int HelloFMI20World_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int HelloFMI20World_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int HelloFMI20World_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int HelloFMI20World_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int HelloFMI20World_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int HelloFMI20World_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int HelloFMI20World_checkForAsserts(DATA *data, threadData_t *threadData);
extern int HelloFMI20World_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int HelloFMI20World_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int HelloFMI20World_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* HelloFMI20World_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* HelloFMI20World_relationDescription(int i);
extern void HelloFMI20World_function_initSample(DATA *data, threadData_t *threadData);
extern int HelloFMI20World_initialAnalyticJacobianG(void* data, threadData_t *threadData);
extern int HelloFMI20World_initialAnalyticJacobianA(void* data, threadData_t *threadData);
extern int HelloFMI20World_initialAnalyticJacobianB(void* data, threadData_t *threadData);
extern int HelloFMI20World_initialAnalyticJacobianC(void* data, threadData_t *threadData);
extern int HelloFMI20World_initialAnalyticJacobianD(void* data, threadData_t *threadData);
extern int HelloFMI20World_functionJacG_column(void* data, threadData_t *threadData);
extern int HelloFMI20World_functionJacA_column(void* data, threadData_t *threadData);
extern int HelloFMI20World_functionJacB_column(void* data, threadData_t *threadData);
extern int HelloFMI20World_functionJacC_column(void* data, threadData_t *threadData);
extern int HelloFMI20World_functionJacD_column(void* data, threadData_t *threadData);
extern const char* HelloFMI20World_linear_model_frame(void);
extern const char* HelloFMI20World_linear_model_datarecovery_frame(void);
extern int HelloFMI20World_mayer(DATA* data, modelica_real** res, short *);
extern int HelloFMI20World_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int HelloFMI20World_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int HelloFMI20World_setInputData(DATA *data, const modelica_boolean file);
extern int HelloFMI20World_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void HelloFMI20World_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void HelloFMI20World_function_updateSynchronous(DATA * data, threadData_t *threadData, long i);
extern int HelloFMI20World_function_equationsSynchronous(DATA * data, threadData_t *threadData, long i);
extern void HelloFMI20World_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void HelloFMI20World_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int HelloFMI20World_inputNames(DATA* data, char ** names);
extern int HelloFMI20World_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int HelloFMI20World_functionLocalKnownVars(DATA*, threadData_t*);
extern int HelloFMI20World_symbolicInlineSystem(DATA*, threadData_t*);

#include "HelloFMI20World_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(HelloFMI20World__MODEL_H) */


