/* Additional record code for HelloFMI20World generated by the OpenModelica Compiler OMCompiler v1.13.0-dev.1097+gde1221967. */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

