# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      # Don't cancel in-progress jobs if any matrix job fails
      fail-fast: false
      matrix:
        julia-version: ['1.5']
        julia-arch: [x64]
        os: [ubuntu-latest]
        experimental: [false]
        include:
          - os: ubuntu-18.04
            julia-version: '1.0'
            julia-arch: x64
            experimental: true
          - os: macOS-latest
            julia-version: '1.5'
            julia-arch: x64
            experimental: true
          - os: windows-latest
            julia-version: '1.5'
            julia-arch: x64
            experimental: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v2

      # Set up Julia
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}

      # Install gfortran3 on Ubuntu for JModelica.org tests
      # See https://github.com/modelica/fmi-cross-check/issues/57
      - name: Install libgfortran3 for JModelica.org
        run: |
              if [ "$RUNNER_OS" == 'Linux' ]; then
                sudo apt install libgfortran3
              fi
        shell: bash

      # Build JuliaFMI package
      - name: "Build package"
        uses: julia-actions/julia-buildpkg@latest

      # Run the tests
      - name: "Run tests"
        uses: julia-actions/julia-runtest@latest

      - name: "Process coverage report"
        uses: julia-actions/julia-processcoverage@v1

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
